# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Report

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore: 
      - '.github/**'
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Jacoco report artifact
      uses: actions/upload-artifact@v1
      with:
        name: jacoco-report
        path: target/site/jacoco/jacoco.xml
  
  report:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Download Jacoco report artifact
      uses: actions/download-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
